site_name: Raspberry Pi Cat Documentation（上田研 自律移動チーム内）
site_url: https://uhobeike.github.io/raspicat_documentation/
site_author: Tatsuhiro Ikebe

repo_name: uhobeike/raspicat_documentation 
repo_url: https://github.com/uhobeike/raspicat_documentation
# repo: fontawesome/brands/github

copyright: Copyright &copy; 2022 Tatsuhiro Ikebe

theme:
    name: material
    language: ja
    logo: 'https://i.gyazo.com/667c1d52a447f38d53cd52beadbb40f1.png'
    favicon: 'https://i.gyazo.com/ed2afbfd0328143ef7e2c0418172348f.png'
    # 使用可能色は定義された21色
    #    red, pink, purple, deep purple, indigo, blue, light blue, cyan,
    #    teal,  green, light green, lime, yellow, amber, orange,
    #    deep orange,   brown, grey, blue grey, white
    font:
        text: 'Roboto'
        code: 'Roboto Mono'
    features:
        - navigation.tabs
        - navigation.top
        - navigation.expand
        - content.code.annotate
        - content.code.copy
        - content.code.select
        - content.code.annotate
    palette:
        - scheme: default
          primary: pink
          accent: pink
          toggle:
              icon: material/toggle-switch-off-outline
              name: ダークモードに切り替えます。

        - scheme: slate
          primary: idigo
          accent: indigo
          toggle:
              icon: material/toggle-switch
              name: ライトモードに切り替えます。
    icon:
      repo: fontawesome/brands/github

extra:
    logo:
        # 利用可能なアイコンは以下を参照
        # https://material.io/resources/icons/?icon=description&style=baseline
        icon: 'developer_board'
    # ウェブアプリマニフェストを有効化
    manifest: 'manifest.webmanifest'
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/uhobeike
      - icon: fontawesome/brands/twitter
        link: https://twitter.com/BEIKE_RE

markdown_extensions:
    - admonition
    - attr_list
    - footnotes
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.superfences
    - footnotes
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.details

nav:

- Home:
  - このサイトについて: index.md
- Document:
  - Raspberry Pi Catについて: document/raspicat_documentaion.md
  - Tutorial:
    - 1 ノートPCのセットアップ: document/tutorial/1_laptopsetup.md 
    - 2 Raspberry Pi Cat シミュレータ: document/tutorial/2_raspicat_simulator.md 
    - 3 Raspberry Piのセットアップ: document/tutorial/3_raspisetup.md 
    - 4 Raspberry Piの無線接続設定: document/tutorial/4_wireless.md 
    - 5 MID-360の接続設定: document/tutorial/5_livox.md 
    - 6 TeleOperation: document/tutorial/6_teleop.md 
    - 7 SLAM: document/tutorial/7_slam.md 
    - 8 Navigation2: document/tutorial/8_nav.md 
    - 9 Nav2 とemcl2 でナビゲーション: document/tutorial/9_navwithemcl.md 
  - Simulator:
    - Raspberry Pi Cat Simulator: document/simulator/raspicat_simulator.md
    - Create Raspberry Pi Cat Simulation World: document/simulator/create_raspicat_simulation_world.md
  - Real Machine:
    - Set Up:
      - 有線LAN（Ethernet）: document/real_machine/set_up/wired.md
      - 無線LAN（Wi-Fi）: document/real_machine/set_up/wireless.md
      - Ethernet LiDAR の接続: document/real_machine/set_up/ethernet_lidar.md
      - Livox MID-360 と Raspberry Piの同時有線接続設定: document/real_machine/set_up/livox_wired.md
    - Clone & Restore:
      - バックアップイメージの取得とリストア: document/real_machine/clone_restore.md
    - Basic Operation: 
      - 基本操作: document/real_machine/basic_operation/basic_operation.md
    - Time Synchronization: 
      - 時刻同期: document/real_machine/time_synchronization/time_synchronization.md
    - Mapping: 
      - 地図作成: document/real_machine/mapping/mapping.md
      - FAST_LIOで地図作成: document/real_machine/mapping/fast_lio.md
    - Navigation:
      - ナビゲーション: document/real_machine/navigation/navigation.md
      - ウェイポイント ナビゲーション: document/real_machine/navigation/waypoint_navigation.md

- Repository: 
  - Raspberry Pi Cat関連のリポジトリ: repository/repository.md
  - Raspberry Pi Cat関連のリポジトリの説明(簡単に): repository/repository_description.md
- Know-how（B3用）:
  - やると良いかも集め: know_how/know_how.md
- Study Meeting:
  - Gitを学ぶ回: study_meeting/2022_git_github/git.md
  - GitHubを学ぶ回: study_meeting/2022_git_github/github.md
  - ROSを学ぶ回（ROSとは）: study_meeting/2022_ros/what_ros.md
  - 詳解確率ロボティクスを読む回:
    - 何をする？: study_meeting/2022_detailed_explanation_probabilistic_robotics/what_to_do.md
    - 第1回 : study_meeting/2022_detailed_explanation_probabilistic_robotics/1.md
    - 第2回 : study_meeting/2022_detailed_explanation_probabilistic_robotics/2.md
    - 第3回 : study_meeting/2022_detailed_explanation_probabilistic_robotics/3.md
    - 第4回 : study_meeting/2022_detailed_explanation_probabilistic_robotics/4.md
- Information:
  - 上田研にある移動ロボット/センサー: information/robot_sensor.md
  - 動画集: information/raspicat_mp4.md
- Chat Corner 💬:
  - News📰 : chat_corner/news.md
  - 要望: chat_corner/request.md
  - エラー集/解決策:
    - Raspberry Pi Cat: chat_corner/error_resolution/raspicat_error_resolution.md
    - Raspberry Pi Cat（WSL2）: chat_corner/error_resolution/raspicat_error_resolution_wsl2.md
    - Raspberry Pi Cat V2: chat_corner/error_resolution/raspicat_v2_error_resolution.md
    - Raspberry Pi Cat V2（WSL2）: chat_corner/error_resolution/raspicat_v2_error_resolution_wsl2.md
  - メモ(誰でもどうぞw): chat_corner/memo.md

